# Generated by Django 5.1.5 on 2025-01-31 15:20

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'Цветовая схема',
                'verbose_name_plural': 'Цветовые схемы',
                'db_table': 'color_scheme',
                'db_table_comment': 'Color Scheme (Grant, TetraPak, Italiano Vero etc)',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LayoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'Catalogue Page Layout Type',
                'verbose_name_plural': 'Тип макета страницы каталога',
                'db_table': 'layout_type',
                'db_table_comment': 'Layout type',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Типы материала',
                'db_table': 'material_type',
                'db_table_comment': 'Material Type (plastic, metal, paper, block printing etc)',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PantoneToHex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('hex', models.CharField(max_length=7, null=True)),
            ],
            options={
                'verbose_name': 'pantone_to_hex',
                'verbose_name_plural': 'pantone_to_hex',
                'db_table': 'pantone_to_hex',
                'db_table_comment': 'PantoneToHex',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('code', models.CharField(max_length=10, verbose_name='код')),
                ('pantone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='PANTONE')),
                ('hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='HEX')),
                ('standard', models.BooleanField(default=True, verbose_name='стандарт')),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web.colorscheme', verbose_name='цветовая схема')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
                'db_table': 'color',
                'db_table_comment': 'Color',
                'ordering': ['color_scheme', 'code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='colorscheme',
            name='color_scheme_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web.materialtype', verbose_name='материал'),
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(default=False, verbose_name='удалено')),
                ('second_name', models.CharField(blank=True, max_length=120, null=True)),
                ('cover', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web/files/cover'), upload_to=django.core.files.storage.FileSystemStorage(location='viki_web/files/cover'))),
                ('product_group_url', models.CharField(max_length=60)),
                ('layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web.layouttype')),
            ],
            options={
                'verbose_name': 'Раздел каталога',
                'verbose_name_plural': 'Разделы каталога',
                'db_table': 'product_group',
                'db_table_comment': 'catalogue sections',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
