# Generated by Django 5.1.5 on 2025-01-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgroup',
            options={'ordering': ['priority', 'name'], 'verbose_name': 'Раздел каталога', 'verbose_name_plural': 'Разделы каталога'},
        ),
        migrations.AddField(
            model_name='productgroup',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
