# Generated by Django 5.1.5 on 2025-02-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web', '0002_alter_productgroup_options_productgroup_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='color_scheme',
        ),
        migrations.RemoveField(
            model_name='colorscheme',
            name='color_scheme_type',
        ),
        migrations.RemoveField(
            model_name='productgroup',
            name='layout',
        ),
        migrations.DeleteModel(
            name='PantoneToHex',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.DeleteModel(
            name='ColorScheme',
        ),
        migrations.DeleteModel(
            name='MaterialType',
        ),
        migrations.DeleteModel(
            name='LayoutType',
        ),
        migrations.DeleteModel(
            name='ProductGroup',
        ),
    ]
