# Generated by Django 5.1.5 on 2025-03-29 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('viki_web_cms', '0035_alter_printdata_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('legal', models.BooleanField(default=True)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(max_length=8)),
                ('ogrn', models.CharField(max_length=13)),
                ('region', models.CharField(max_length=2)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Клиент (группа)',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'company',
                'db_table_comment': 'Company',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('account_no', models.CharField(max_length=20)),
                ('bic', models.CharField(max_length=9)),
                ('corr_account', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=140)),
                ('city', models.CharField(max_length=140)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_customer.company')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
                'db_table': 'bank_account',
                'db_table_comment': 'BankAccount',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('e_mail_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_price_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.standardpricetype')),
            ],
            options={
                'verbose_name': 'Клиент (группа)',
                'verbose_name_plural': 'Клиенты',
                'db_table': 'customer',
                'db_table_comment': 'Customer',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_customer.customer'),
        ),
    ]
