# Generated by Django 5.1.5 on 2025-02-04 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('hex', models.CharField(max_length=7)),
            ],
            options={
                'verbose_name': 'Цветовая группа',
                'verbose_name_plural': 'Цветовые группы',
                'db_table': 'color_group',
                'db_table_comment': 'nearest color',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
