# Generated by Django 5.1.5 on 2025-02-04 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0002_colorgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='color_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.colorgroup', verbose_name='цветовая группа'),
        ),
    ]
