# Generated by Django 5.1.5 on 2025-02-08 05:33

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0003_color_color_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('option_article', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Модификация товара',
                'verbose_name_plural': 'Модификации товаров',
                'db_table': 'goods_options',
                'db_table_comment': 'Goods options',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('article', models.CharField(max_length=120)),
                ('additional_material', models.BooleanField(default=False)),
                ('details_number', models.IntegerField(default=1)),
                ('multicolor', models.BooleanField(default=False)),
                ('print_layout', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/goods'), upload_to=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/goods'))),
                ('additional_color_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_color_scheme', to='viki_web_cms.colorscheme')),
                ('color_scheme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='color_scheme', to='viki_web_cms.colorscheme')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'db_table': 'goods',
                'db_table_comment': 'goods',
                'ordering': ['article', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsToOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.goods')),
                ('goods_options', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.goodsoptions')),
            ],
            options={
                'verbose_name': 'Связь модификация-товар',
                'verbose_name_plural': 'Связи модификация-товар',
                'db_table': 'goods_to_options',
                'db_table_comment': 'Goods  to options',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
