# Generated by Django 5.1.5 on 2025-02-08 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0004_goodsoptions_goods_goodstooptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsOptions',
            new_name='GoodsOption',
        ),
        migrations.RenameModel(
            old_name='GoodsToOptions',
            new_name='GoodsToOption',
        ),
    ]
