# Generated by Django 5.1.5 on 2025-02-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0005_rename_goodsoptions_goodsoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('goods_group_url', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Группа товара',
                'verbose_name_plural': 'Группы товаров',
                'db_table': 'goods_group',
                'db_table_comment': 'Goods group',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
