# Generated by Django 5.1.5 on 2025-02-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0006_goodsgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'Print Place',
                'verbose_name_plural': 'Место нанесения',
                'db_table': 'print_place',
                'db_table_comment': 'Print place',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'Print Type',
                'verbose_name_plural': 'Тип нанесения',
                'db_table': 'print_type',
                'db_table_comment': 'Print type',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
