# Generated by Django 5.1.5 on 2025-02-09 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0007_printplace_printtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.goodsgroup'),
        ),
        migrations.AddField(
            model_name='goods',
            name='product_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.productgroup'),
        ),
    ]
