# Generated by Django 5.1.5 on 2025-02-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0008_goods_goods_group_goods_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'Фильтр',
                'verbose_name_plural': 'Фильтры',
                'db_table': 'filter_options',
                'db_table_comment': 'Filter Options',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterToGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('filter_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.filteroption')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
            ],
            options={
                'verbose_name': 'Фильтр товара',
                'verbose_name_plural': 'Фильтры товара',
                'db_table': 'filter_goods',
                'db_table_comment': 'Filter Goods',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilterToGoodsGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('filter_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.filteroption')),
                ('goods_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goodsgroup')),
            ],
            options={
                'verbose_name': 'Фильтр группы товара',
                'verbose_name_plural': 'Фильтры группы товара',
                'db_table': 'filter_goods_group',
                'db_table_comment': 'Filter Goods Group',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
