# Generated by Django 5.1.5 on 2025-02-23 06:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0009_filteroption_filtertogoods_filtertogoodsgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('item_article', models.CharField(max_length=120)),
                ('image', models.FileField(blank=True, null=True, upload_to='viki_web_cms/files/item_photo/')),
                ('simple_article', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
                ('main_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.color')),
            ],
            options={
                'verbose_name': 'Позиция каталога',
                'verbose_name_plural': 'Позиции каталога',
                'db_table': 'catalogue_item',
                'db_table_comment': 'Catalogue Item',
                'ordering': ['goods__article', 'goods__name', 'main_color__code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogueItemColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('color_position', models.IntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(9)])),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.color')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.catalogueitem')),
            ],
            options={
                'verbose_name': 'Дополнительный цвет',
                'verbose_name_plural': 'Дополнительные цвета',
                'db_table': 'catalogue_item_color',
                'db_table_comment': 'Catalogue Item Color',
                'ordering': ['item__goods__article', 'item__goods__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalogueItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.catalogueitem')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goodsoption')),
            ],
            options={
                'verbose_name': 'Опция позиции каталога',
                'verbose_name_plural': 'Опции позиций каталога',
                'db_table': 'catalogue_item_option',
                'db_table_comment': 'Catalogue Item Option',
                'ordering': ['item__goods__article', 'item__goods__name'],
                'abstract': False,
            },
        ),
    ]
