# Generated by Django 5.1.5 on 2025-02-23 06:14

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0010_catalogueitem_catalogueitemcolor_catalogueitemoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueitem',
            name='image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/item_photo'), upload_to=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/item_photo')),
        ),
    ]
