# Generated by Django 5.1.5 on 2025-03-04 05:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0013_remove_goods_print_layout_goods_standard_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('price_list_date', models.DateField(default=django.utils.timezone.now)),
                ('promotion_price', models.BooleanField(default=False)),
                ('promotion_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Price List Date',
                'verbose_name_plural': 'Price List Dates',
                'db_table': 'price',
                'db_table_comment': 'price',
                'ordering': ['-price_list_date'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceGoodsStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('customer_price', models.FloatField()),
                ('agency_one_price', models.FloatField()),
                ('agency_two_price', models.FloatField()),
                ('dealer', models.BooleanField(default=True)),
                ('dealer_price', models.FloatField()),
                ('retail_price', models.FloatField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
                ('goods_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.goodsgroup')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.price')),
            ],
            options={
                'verbose_name': 'Goods Price',
                'verbose_name_plural': 'Goods Prices',
                'db_table': 'goods_price',
                'db_table_comment': 'goods price',
                'ordering': ['goods__product_group__priority', 'goods__article', 'goods__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceItemStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('customer_price', models.FloatField()),
                ('agency_one_price', models.FloatField()),
                ('agency_two_price', models.FloatField()),
                ('dealer', models.BooleanField(default=True)),
                ('dealer_price', models.FloatField()),
                ('retail_price', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.catalogueitem')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.price')),
            ],
            options={
                'verbose_name': 'Item Price',
                'verbose_name_plural': 'Item Prices',
                'db_table': 'item_price',
                'db_table_comment': 'item price',
                'ordering': ['item__item_article'],
                'abstract': False,
            },
        ),
    ]
