# Generated by Django 5.1.5 on 2025-03-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0014_price_pricegoodsstandard_priceitemstandard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricegoodsstandard',
            old_name='dealer',
            new_name='retail',
        ),
        migrations.AddField(
            model_name='goods',
            name='dealer_price',
            field=models.BooleanField(default=True),
        ),
    ]
