# Generated by Django 5.1.5 on 2025-03-06 06:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0015_rename_dealer_pricegoodsstandard_retail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardPriceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('field_name', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Тип цены',
                'verbose_name_plural': 'Типы цен',
                'db_table': 'standard_price_type',
                'db_table_comment': 'standard price type',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('discount', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('price_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.standardpricetype', unique=True)),
            ],
            options={
                'verbose_name': 'Скидка партнера',
                'verbose_name_plural': 'Скидки партнеров',
                'db_table': 'customer_discount',
                'db_table_comment': 'customer discount',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolumeDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('discount', models.FloatField(validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)])),
                ('volume', models.IntegerField()),
                ('price_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.standardpricetype')),
            ],
            options={
                'verbose_name': 'Скидка партнера',
                'verbose_name_plural': 'Скидки партнеров',
                'db_table': 'price_discount',
                'db_table_comment': 'price discount',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
