# Generated by Django 5.1.5 on 2025-03-06 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0016_standardpricetype_customerdiscount_volumediscount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpricetype',
            name='field_name',
        ),
    ]
