# Generated by Django 5.1.5 on 2025-03-06 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0017_remove_standardpricetype_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdiscount',
            name='id',
        ),
        migrations.AlterField(
            model_name='customerdiscount',
            name='price_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='viki_web_cms.standardpricetype'),
        ),
    ]
