# Generated by Django 5.1.5 on 2025-03-06 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0018_remove_customerdiscount_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerDiscount',
        ),
    ]
