# Generated by Django 5.1.5 on 2025-03-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0020_alter_volumediscount_table_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceitemstandard',
            name='item',
        ),
        migrations.RemoveField(
            model_name='priceitemstandard',
            name='price_list',
        ),
        migrations.DeleteModel(
            name='PriceGoodsStandard',
        ),
        migrations.DeleteModel(
            name='PriceItemStandard',
        ),
    ]
