# Generated by Django 5.1.5 on 2025-03-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0022_pricegoodsstandard_priceitemstandard'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdiscount',
            options={'ordering': ['price_name__priority'], 'verbose_name': 'Скидка партнера', 'verbose_name_plural': 'Скидки партнеров'},
        ),
        migrations.AlterModelOptions(
            name='standardpricetype',
            options={'ordering': ['priority'], 'verbose_name': 'Тип цены', 'verbose_name_plural': 'Типы цен'},
        ),
        migrations.AlterModelOptions(
            name='volumediscount',
            options={'ordering': ['price_name__priority'], 'verbose_name': 'Скидка партнера', 'verbose_name_plural': 'Скидки партнеров'},
        ),
        migrations.AddField(
            model_name='standardpricetype',
            name='priority',
            field=models.SmallIntegerField(default=10),
        ),
    ]
