# Generated by Django 5.1.5 on 2025-03-09 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0023_alter_customerdiscount_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceGoodsQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Price Goods Quantity',
                'verbose_name_plural': 'Price Goods Quantities',
                'db_table': 'price_goods_quantity',
                'db_table_comment': 'price goods',
                'ordering': ['quantity'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceGoodsVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('price', models.FloatField(default=0)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.price')),
                ('price_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.standardpricetype')),
                ('price_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.pricegoodsquantity')),
            ],
            options={
                'verbose_name': 'Goods Price Volume',
                'verbose_name_plural': 'Goods Prices Volume',
                'db_table': 'goods_price_volume',
                'db_table_comment': 'goods price volume',
                'ordering': ['price_volume', 'goods__product_group__priority', 'goods__article', 'goods__name'],
                'abstract': False,
            },
        ),
    ]
