# Generated by Django 5.1.5 on 2025-03-10 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0024_pricegoodsquantity_pricegoodsvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPriceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('print_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printtype')),
            ],
            options={
                'verbose_name': 'Print Price Group',
                'verbose_name_plural': 'Группы нанесения',
                'db_table': 'print_price_group',
                'db_table_comment': 'Print price group',
                'ordering': ['print_type', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('quantity', models.IntegerField()),
                ('print_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printtype')),
            ],
            options={
                'verbose_name': 'Print Volume',
                'verbose_name_plural': 'Тиражи нанесения',
                'db_table': 'print_volume',
                'db_table_comment': 'Print volume',
                'ordering': ['print_type', 'quantity'],
                'abstract': False,
            },
        ),
    ]
