# Generated by Django 5.1.5 on 2025-03-10 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0025_printpricegroup_printvolume'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintGroupToGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
                ('print_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printplace')),
                ('print_price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printpricegroup')),
            ],
            options={
                'verbose_name': 'Print Group To Goods',
                'verbose_name_plural': 'Print Group to Goods',
                'db_table': 'print_group_to_goods',
                'db_table_comment': 'print group to goods',
                'ordering': ['print_price_group', 'goods__article', 'goods__name'],
                'abstract': False,
            },
        ),
    ]
