# Generated by Django 5.1.5 on 2025-03-10 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0026_printgrouptogoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('price', models.FloatField(default=0)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.price')),
                ('print_price_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printpricegroup')),
                ('print_volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printvolume')),
            ],
            options={
                'verbose_name': 'Print Price',
                'verbose_name_plural': 'Print Price List',
                'db_table': 'print_price',
                'db_table_comment': 'print price list',
                'ordering': ['print_price_group__print_type', 'print_volume__quantity'],
                'abstract': False,
            },
        ),
    ]
