# Generated by Django 5.1.5 on 2025-03-12 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0027_printprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
            ],
            options={
                'verbose_name': 'Parts Description',
                'verbose_name_plural': 'Parts Descriptions',
                'db_table': 'parts_description',
                'db_table_comment': 'parts description',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('description', models.CharField(max_length=250)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
            ],
            options={
                'verbose_name': 'Goods Description',
                'verbose_name_plural': 'Goods Descriptions',
                'db_table': 'goods_description',
                'db_table_comment': 'goods description',
                'ordering': ['goods__article', 'goods__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('position', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
                ('parts_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.partsdescription')),
            ],
            options={
                'verbose_name': 'Article Description',
                'verbose_name_plural': 'Article Descriptions',
                'db_table': 'article_description',
                'db_table_comment': 'article description',
                'ordering': ['goods__article', 'goods__name'],
                'abstract': False,
            },
        ),
    ]
