# Generated by Django 5.1.5 on 2025-03-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0028_partsdescription_goodsdescription_articledescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
