# Generated by Django 5.1.5 on 2025-03-12 11:30

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0029_goods_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('length', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Размеры товара',
                'verbose_name_plural': 'Размеры товаров',
                'db_table': 'goods_dimensions',
                'db_table_comment': 'Goods dimensions',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('layout', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/layout'), upload_to='')),
            ],
            options={
                'verbose_name': 'Шаблон нанесения',
                'verbose_name_plural': 'Шаблоны нанесения',
                'db_table': 'print_layout',
                'db_table_comment': 'Print Layout',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('length', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('color_quantity', models.IntegerField(default=2)),
                ('place_quantity', models.IntegerField(default=1)),
                ('print_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printplace')),
                ('print_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printtype')),
            ],
            options={
                'verbose_name': 'Данные печати',
                'verbose_name_plural': 'Данные печати',
                'db_table': 'printing_data',
                'db_table_comment': 'Printing data',
                'ordering': ['print_type', 'print_place'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printlayout')),
            ],
            options={
                'verbose_name': 'Шаблон для товара',
                'verbose_name_plural': 'Шаблоны для товара',
                'db_table': 'goods_layout',
                'db_table_comment': 'Goods Layout',
                'ordering': ['goods__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrintOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.goods')),
                ('print_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.printdata')),
            ],
            options={
                'verbose_name': 'Возможности печати',
                'verbose_name_plural': 'Возможности печати',
                'db_table': 'print_opportunity',
                'db_table_comment': 'Print opportunity',
                'ordering': ['print_data__print_type', 'print_data__print_place'],
                'abstract': False,
            },
        ),
    ]
