# Generated by Django 5.1.5 on 2025-03-13 19:46

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('viki_web_cms', '0030_goodsdimensions_printlayout_printdata_goodslayout_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articledescription',
            options={'ordering': ['goods__article', 'goods__name', 'position'], 'verbose_name': 'Article Description', 'verbose_name_plural': 'Article Descriptions'},
        ),
        migrations.AddField(
            model_name='standardpricetype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='printlayout',
            name='layout',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='static/viki_web_cms/files/layout'), upload_to=''),
        ),
    ]
