# Generated by Django 5.1.5 on 2025-03-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0036_company_bankaccount_customer_company_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='standard_price_type',
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
