# Generated by Django 5.1.5 on 2025-03-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0038_company_bankaccount_customer_company_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(max_length=9),
        ),
    ]
