# Generated by Django 5.1.5 on 2025-03-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0039_alter_company_kpp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
    ]
