# Generated by Django 5.1.5 on 2025-03-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0041_userphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphone',
            name='phone',
            field=models.CharField(max_length=18),
        ),
    ]
