# Generated by Django 5.1.5 on 2025-03-31 04:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0042_alter_userphone_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPhone',
            new_name='UserExtension',
        ),
        migrations.AlterModelOptions(
            name='userextension',
            options={'ordering': ['user__last_name'], 'verbose_name': 'Доп. информация о пользователе', 'verbose_name_plural': 'Доп. информация о пользователе'},
        ),
        migrations.AlterModelTableComment(
            name='userextension',
            table_comment='UserExtension',
        ),
        migrations.AlterModelTable(
            name='userextension',
            table='user_extension',
        ),
    ]
