# Generated by Django 5.1.5 on 2025-03-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0043_rename_userphone_userextension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='alias',
            field=models.CharField(default='proecopen.ru', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userextension',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.customer'),
        ),
    ]
