# Generated by Django 5.1.5 on 2025-03-31 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0045_alter_userextension_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardpricetype',
            name='group',
        ),
    ]
