# Generated by Django 5.1.5 on 2025-03-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0046_remove_standardpricetype_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userextension',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
