# Generated by Django 5.1.5 on 2025-03-31 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0047_customer_new_userextension_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='vat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='vat',
            field=models.BooleanField(default=False),
        ),
    ]
