# Generated by Django 5.1.5 on 2025-04-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0048_company_vat_customer_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueitem',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goods',
            name='new',
            field=models.BooleanField(default=False),
        ),
    ]
