# Generated by Django 5.1.5 on 2025-04-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0049_catalogueitem_new_goods_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
