# Generated by Django 5.1.5 on 2025-04-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0050_goods_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
