# Generated by Django 5.1.5 on 2025-04-12 04:26

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0051_alter_goods_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('add_photo', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/viki_web_cms/files/item_add_photo'), upload_to='')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.catalogueitem')),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Дополнительные фото',
                'db_table': 'catalogue_item_photo',
                'db_table_comment': 'Catalogue Item Photo',
                'ordering': ['item__goods__article', 'item__goods__name'],
                'abstract': False,
            },
        ),
    ]
