# Generated by Django 5.1.5 on 2025-04-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0052_catalogueitemphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogueitemphoto',
            options={'ordering': ['item__item_article'], 'verbose_name': 'Дополнительное фото', 'verbose_name_plural': 'Дополнительные фото'},
        ),
    ]
