# Generated by Django 5.1.5 on 2025-04-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0053_alter_catalogueitemphoto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsRelated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('main_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_related', to='viki_web_cms.goods')),
                ('related_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related', to='viki_web_cms.goods')),
            ],
            options={
                'verbose_name': 'Сопутствующий товар',
                'verbose_name_plural': 'Сопутствующие товары',
                'db_table': 'related_goods',
                'db_table_comment': 'Related goods',
                'ordering': ['main_goods__article', 'main_goods__name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoodsSimilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('main_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_similar', to='viki_web_cms.goods')),
                ('similar_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar', to='viki_web_cms.goods')),
            ],
            options={
                'verbose_name': 'Похожий товар',
                'verbose_name_plural': 'Похожие товары',
                'db_table': 'similar_goods',
                'db_table_comment': 'Similar goods',
                'ordering': ['main_goods__article', 'main_goods__name'],
                'abstract': False,
            },
        ),
    ]
