# Generated by Django 5.1.5 on 2025-04-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0054_goodsrelated_goodssimilar'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='short_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
