# Generated by Django 5.1.5 on 2025-04-19 05:46

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0055_productgroup_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='printopportunity',
            options={'ordering': ['goods', 'print_data__print_type', 'print_data__print_place'], 'verbose_name': 'Возможности печати', 'verbose_name_plural': 'Возможности печати'},
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='cover',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/cover'), upload_to=''),
        ),
    ]
