# Generated by Django 5.1.5 on 2025-04-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0056_alter_printopportunity_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('short_name', models.CharField(max_length=4)),
                ('address', models.CharField(max_length=255)),
                ('inn', models.CharField(max_length=12)),
                ('kpp', models.CharField(max_length=7)),
                ('ogrn', models.CharField(max_length=13)),
                ('vat', models.BooleanField(default=False)),
                ('priority', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Наша компания',
                'verbose_name_plural': 'Наши компании',
                'db_table': 'our_company',
                'db_table_comment': 'our companies',
                'ordering': ['short_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OurBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('short_name', models.CharField(max_length=4)),
                ('bank_account', models.CharField(max_length=20)),
                ('bic', models.CharField(max_length=9)),
                ('corr_account', models.CharField(max_length=20)),
                ('bank_city', models.CharField(max_length=120)),
                ('priority', models.IntegerField()),
                ('our_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.ourcompany')),
            ],
            options={
                'verbose_name': 'Наша банк',
                'verbose_name_plural': 'Наши банки',
                'db_table': 'our_bank',
                'db_table_comment': 'our banks',
                'ordering': ['short_name'],
                'abstract': False,
            },
        ),
    ]
