# Generated by Django 5.1.5 on 2025-04-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0057_ourcompany_ourbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcompany',
            name='kpp',
            field=models.CharField(max_length=9),
        ),
    ]
