# Generated by Django 5.1.5 on 2025-04-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0058_alter_ourcompany_kpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Опция доставки',
                'verbose_name_plural': 'Опции доставки',
                'db_table': 'delivery_options',
                'db_table_comment': 'delivery options',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
