# Generated by Django 5.1.8 on 2025-05-01 19:38

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0059_deliveryoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('order', models.IntegerField(default=1)),
                ('action', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Состояние заказа',
                'verbose_name_plural': 'Состояния заказа',
                'db_table': 'order_state',
                'db_table_comment': 'order state',
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=17)),
                ('order_date', models.DateField()),
                ('days_to_deliver', models.IntegerField(null=True)),
                ('total_amount', models.FloatField()),
                ('delivery_date', models.DateField(null=True)),
                ('customer_comment', models.CharField(max_length=400, null=True)),
                ('branding_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/order/branding'), upload_to='')),
                ('invoice_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/order/invoice'), upload_to='')),
                ('order_file', models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/order/order'), upload_to='')),
                ('state_changed_at', models.DateTimeField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.company')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.customer')),
                ('our_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.ourcompany')),
                ('user_edited', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_extension', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.userextension')),
                ('previous_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_orders', to='viki_web_cms.orderstate')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='viki_web_cms.orderstate')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'order',
                'db_table_comment': 'order',
                'ordering': ['-order_date', 'order_no'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_price', models.FloatField()),
                ('branding_name', models.CharField(max_length=120)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.catalogueitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.order')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
                'db_table': 'order_item',
                'db_table_comment': 'order item',
                'ordering': ['-order__order_date', 'order__order_no', 'item__item_article'],
            },
        ),
        migrations.CreateModel(
            name='OrderItemBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.IntegerField()),
                ('second_pass', models.BooleanField()),
                ('price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.orderitem')),
                ('print_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.printplace')),
                ('print_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='viki_web_cms.printtype')),
            ],
            options={
                'verbose_name': 'Брендирование товара в заказе',
                'verbose_name_plural': 'Брендирования товара в заказе',
                'db_table': 'order_item_branding',
                'db_table_comment': 'order item branding',
                'ordering': ['-order_item__order__order_date', 'order_item__order__order_no', 'order_item__item__item_article', 'print_type', 'print_place'],
            },
        ),
    ]
