# Generated by Django 5.1.8 on 2025-05-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0062_order_user_responsible_alter_order_user_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiscount',
            name='discount_code',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
