# Generated by Django 5.1.8 on 2025-05-04 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0063_customerdiscount_discount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_option', to='viki_web_cms.deliveryoption'),
        ),
    ]
