# Generated by Django 5.1.8 on 2025-05-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0064_order_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_short_number',
            field=models.IntegerField(default=1),
        ),
    ]
