# Generated by Django 5.1.8 on 2025-05-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0065_order_order_short_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_short_number',
            field=models.IntegerField(),
        ),
    ]
