# Generated by Django 5.1.8 on 2025-05-08 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0066_alter_order_order_short_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateTimeField()),
                ('comment', models.CharField(max_length=400)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.order')),
            ],
            options={
                'verbose_name': 'Комментарий к заказу',
                'verbose_name_plural': 'Комментарии к заказу',
                'db_table': 'order_comment',
                'db_table_comment': 'order comment',
                'ordering': ['-order__order_date', 'order__order_no', '-comment_date'],
            },
        ),
    ]
