# Generated by Django 5.1.8 on 2025-05-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0067_ordercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercomment',
            name='comment_date',
            field=models.DateField(),
        ),
    ]
