# Generated by Django 5.1.8 on 2025-05-08 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0068_alter_ordercomment_comment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_date', models.DateField()),
                ('email_recipient', models.CharField(max_length=200)),
                ('comment', models.CharField(max_length=400)),
                ('attachments', models.CharField(max_length=400)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.order')),
            ],
            options={
                'verbose_name': 'Почтовое сообщение к заказу',
                'verbose_name_plural': 'Почтовые сообщения к заказу',
                'db_table': 'order_mail_log',
                'db_table_comment': 'order mail log',
                'ordering': ['-order__order_date', 'order__order_no', '-email_date'],
            },
        ),
    ]
