# Generated by Django 5.1.8 on 2025-05-09 07:13

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0071_alter_ordermaillog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/order/delivery'), upload_to=''),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='alternate_message_text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='attachments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='branding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='from_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='message_text',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='order_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderstate',
            name='two_messages',
            field=models.BooleanField(default=False),
        ),
    ]
