# Generated by Django 5.1.8 on 2025-05-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0072_order_delivery_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermaillog',
            name='attachments',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
