# Generated by Django 5.1.8 on 2025-05-09 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0073_alter_ordermaillog_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('invoice_date', models.DateField()),
                ('invoice_no', models.CharField(max_length=400)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viki_web_cms.order')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'invoice',
                'db_table_comment': 'invoice',
                'ordering': ['-order__order_date', 'order__order_no', '-invoice_date'],
                'abstract': False,
            },
        ),
    ]
