# Generated by Django 5.1.8 on 2025-05-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0074_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_file',
        ),
        migrations.RemoveField(
            model_name='orderstate',
            name='order_file',
        ),
    ]
