# Generated by Django 5.1.8 on 2025-05-10 10:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0075_remove_order_order_file_remove_orderstate_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcompany',
            name='signature',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='viki_web_cms/files/our_company/signature'), upload_to=''),
        ),
    ]
