# Generated by Django 5.1.8 on 2025-05-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0076_ourcompany_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='branding_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
