# Generated by Django 5.1.8 on 2025-05-15 04:48

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0077_alter_orderitem_branding_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='branding_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='static/viki_web_cms/files/order/branding'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='static/viki_web_cms/files/order/delivery'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='static/viki_web_cms/files/order/invoice'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='cover',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/viki_web_cms/files/cover'), upload_to=''),
        ),
    ]
