# Generated by Django 5.1.8 on 2025-05-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0078_alter_order_branding_file_alter_order_delivery_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=1),
        ),
    ]
