# Generated by Django 5.1.8 on 2025-05-24 19:23

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0079_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='название')),
                ('deleted', models.BooleanField(db_default=False, default=False, verbose_name='удалено')),
                ('main_text', models.CharField(blank=True, max_length=400, null=True)),
                ('second_text', models.CharField(blank=True, max_length=400, null=True)),
                ('image', models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/viki_web_cms/files/news'), upload_to='')),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
                'db_table_comment': 'news',
                'ordering': ['-date'],
                'abstract': False,
            },
        ),
    ]
