# Generated by Django 5.1.8 on 2025-06-08 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0080_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='vat',
        ),
    ]
