# Generated by Django 5.1.8 on 2025-06-08 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0081_remove_customer_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
