# Generated by Django 5.1.8 on 2025-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0082_alter_company_kpp_alter_company_ogrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
