# Generated by Django 5.1.8 on 2025-06-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0083_alter_company_ogrn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Юридические лица'},
        ),
    ]
