# Generated by Django 5.1.8 on 2025-11-03 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('viki_web_cms', '0084_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, help_text='До 70 символов для Google', max_length=70, null=True, verbose_name='SEO заголовок')),
                ('description', models.CharField(blank=True, help_text='До 160 символов для сниппета', max_length=160, null=True, verbose_name='SEO описание')),
                ('keywords', models.CharField(blank=True, help_text='Через запятую', max_length=255, null=True, verbose_name='Ключевые слова')),
                ('text', models.TextField(blank=True, help_text='Текст для индексации (отображается внизу страницы)', null=True, verbose_name='SEO текст')),
                ('og_title', models.CharField(blank=True, max_length=95, null=True, verbose_name='OG заголовок')),
                ('og_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='OG описание')),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/og_images/', verbose_name='OG изображение')),
                ('canonical_url', models.URLField(blank=True, null=True, verbose_name='Канонический URL')),
                ('noindex', models.BooleanField(default=False, verbose_name='Запретить индексацию')),
                ('nofollow', models.BooleanField(default=False, verbose_name='Запретить следование по ссылкам')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'SEO',
                'verbose_name_plural': 'SEO данные',
                'db_table': 'seo',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='seo_content_a54353_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
