# Generated by Django 5.1.8 on 2025-11-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0085_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seo',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
