# Generated by Django 5.1.8 on 2025-11-03 10:36

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viki_web_cms', '0086_seo_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={'ordering': ['name'], 'verbose_name': 'SEO', 'verbose_name_plural': 'SEO данные'},
        ),
        migrations.RemoveIndex(
            model_name='seo',
            name='seo_content_a54353_idx',
        ),
        migrations.AlterUniqueTogether(
            name='seo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='goods',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods', to='viki_web_cms.seo'),
        ),
        migrations.AddField(
            model_name='productgroup',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_groups', to='viki_web_cms.seo'),
        ),
        migrations.AddField(
            model_name='seo',
            name='name',
            field=models.CharField(default='none', max_length=140, verbose_name='название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seo',
            name='deleted',
            field=models.BooleanField(db_default=False, default=False, verbose_name='удалено'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='og_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='static/viki_web_cms/files/og_images'), upload_to='', verbose_name='OG изображение'),
        ),
        migrations.RemoveField(
            model_name='seo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='object_id',
        ),
    ]
